---
title: "NYC Public School Lead Data"
output: 
  flexdashboard::flex_dashboard:
    orientation: row
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(janitor)
library(stringr)
library(forcats)
library(httr)
library(plotly)
library(dplyr)
library(shiny)
library(devtools)
library(leaflet)
library(rgdal)
```

```{r read_lead, message = FALSE, warning = FALSE}
#read in lead data, restrict to NYC counties
lead_data <- GET("https://health.data.ny.gov/resource/ja9d-vnbi.csv", query = list(`$limit` = 5000)) %>% 
  content("parsed") %>% 
  clean_names() %>% 
  filter(county %in% c("Queens", "Kings", "New York", "Bronx", "Richmond")) %>% 
  select(school_number = school, location, any_lead_free_buildings, number_of_outlets_result_less, 
         number_of_outlets_result_greater, number_of_outlets, county, school_district)
```

```{r read_lead_free, message = FALSE, warning = FALSE}
#read in lead data, restrict to NYC counties
lead_free_data <- GET("https://health.data.ny.gov/resource/mn8r-98tx.csv", query = list(`$limit` = 5000)) %>% 
  content("parsed") %>% 
  clean_names() %>% 
  filter(county %in% c("Queens", "Kings", "New York", "Bronx", "Richmond")) %>% 
  select(school_number = school, county, school_district)
```

```{r read_demo, message = FALSE, warning = FALSE}
#read in demographic characteristics, create "school_number" to merge with lead data
demo_data <- GET("https://data.cityofnewyork.us/resource/vjn2-hei2.csv", query = list(`$limit` = 2000)) %>% 
  content("parsed") %>% 
  clean_names() %>% 
  select(dbn, school_name, asian, black, english_language_learners, 
         hispanic, other_race = other, poverty, students_with_disabilities,
         white) %>% 
  mutate(asian = as.numeric(asian), asian = round(asian, 4), #convert proportions to numeric
         black = as.numeric(black), black = round(black, 4),
         english_language_learners = as.numeric(english_language_learners), 
         english_language_learners = round(english_language_learners, 4),
         hispanic = as.numeric(hispanic), hispanic = round(hispanic, 4),
         other_race = as.numeric(other_race), other_race = round(other_race, 4),
         poverty = as.numeric(poverty), poverty = round(poverty, 4),
         white = as.numeric(white), white = round(white, 4),
         students_with_disabilities = as.numeric(students_with_disabilities), 
         students_with_disabilities = round(students_with_disabilities, 4)) %>% # round proportions
  mutate(school_number = str_replace(dbn, "^..", "")) #create school number to merge with lead data
```

```{r read_scores, message = FALSE, warning = FALSE}
#read in school math scores, restrict to 2017
score_data <- GET("https://data.cityofnewyork.us/resource/stka-4ti9.csv", query = list(`$limit` = 25000)) %>% 
  content("parsed") %>% 
  clean_names() %>% 
  filter(year == 2017 & grade == "All Grades") %>% #so that testst scores are AFTER lead measurement
  select(dbn, school_name, grade, mean_scale_score)
```

```{r merge, message = FALSE, warning = FALSE}
#merge demographic characteristics with math scores
school_data <- left_join(demo_data, score_data, by = c("dbn"))

#merge demographic characteristics and math scores with lead data
all_data <- left_join(school_data, lead_data, by = "school_number") %>% 
  filter(mean_scale_score != "s") %>% 
  mutate(mean_scale_score = as.numeric(mean_scale_score),
         lead_percent = number_of_outlets_result_greater / number_of_outlets, #percent of outlets with lead
         minority = ifelse(white > 0.5, "White", "Minority")) %>% 
  select(-school_name.y, -dbn) %>% 
  mutate(location = str_replace(location, "POINT \\(", ""),
         location = str_replace(location, "\\)", "")) %>% 
  separate(location, into = c("longitude", "latitude"), sep = " ") %>% #separate lat and long
  mutate(largest = pmax(white, black, asian, hispanic, other_race)) %>% 
  mutate(race = ifelse(largest == white, "White", #create categorical race category
                      ifelse(largest == black, "Black",
                             ifelse(largest == hispanic, "Hispanic",
                                    ifelse(largest == asian, "Asian",
                                           ifelse(largest == other_race, "Other", "Missing"))))),
         latitude = as.numeric(latitude),
         longitude = as.numeric(longitude)) %>% 
  mutate(lead_med = ifelse(lead_percent > median(lead_percent, na.rm = TRUE), "High", "Low"))

eda_data <- all_data %>% 
  select(school_number, english_language_learners, hispanic, other_race, poverty,
         students_with_disabilities, white, asian, black, grade, mean_scale_score,
         any_lead_free_buildings, lead_percent, minority, race, lead_med)

pal_race <- colorFactor(c("#F8766D", "#00BFC4", "#C77CFF", "#00BA38"), all_data$race)

pal_lead <- colorFactor(c("#C77CFF", "#00BFC4"), all_data$lead_med)
```


Column {.sidebar}
-----------------------------------------------------------------------

```{r}
# selectInput widget
school_choice = all_data %>% distinct(school_name.x) %>% pull()

selectInput("school_choice", label = h3("Select School"),
            choices = school_choice, selected = "15K839 - M.S. 839")

# radioButtons widget
lead_choice = all_data %>%
  distinct(lead_med) %>% 
  drop_na() %>% 
  pull()

radioButtons("lead_choice", label = h3("Choose Lead Proportion"),
    choices = lead_choice, 
    selected = "High")
data <- reactive(subset(all_data, name == input$lead_med))

```

Row
-----------------------------------------------------------------------

### NYC Schools By Median Lead Exposure

```{r}

ui <- fluidPage(
  leafletOutput("mymap"),
  p(),
  actionButton("lead_med", "New points")
)

server <- function(input, output, session) {

  points <- eventReactive(input$lead_med, {
    cbind(rnorm(40) * 2 + 13, rnorm(40) + 48)
  }, ignoreNULL = FALSE)

  output$mymap <- renderLeaflet({all_data %>%
  mutate(content = str_c("School: ", school_number,
                 "\n Race: ", race, 
                 "\n Poverty: ", poverty)) %>% 
  leaflet() %>% 
  addTiles() %>% 
  addCircles(~longitude, ~latitude, 
             label = ~content, color = ~pal_lead(lead_med), fillOpacity = 3) %>% 
  addLegend(position = "bottomright", pal = pal_lead, values = ~lead_med,
            title = "Lead Proportion", opacity = 3)
})
}

shinyApp(ui, server)

```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Lead and Minority Status

```{r}

renderPlot({eda_data %>%
  ggplot(aes(y = lead_percent, x = race, fill = race)) + 
  geom_violin() + scale_fill_brewer(palette = "Pastel2") +
  labs(x = "Figure 2. Race/Ethnicity", y = "Proportion of pipes with lead > 15 ppb",
       title = "Race/Ethnicity and Lead Exposure") +
       theme(legend.position = "none")
})

```

### Race and Standardized Test Scores

```{r}
renderPlot({eda_data %>% 
  ggplot(aes(y = mean_scale_score, x = race, fill = race)) + 
  geom_violin() + scale_fill_brewer(palette = "Pastel2") +
  labs(y = "Standardized math test scores", x = "Race/Ethnicity",
       title = "Figure 4. Race/Ethnicity and student math scores") +
  theme(legend.position = "none")
})

```

